import { ExperienceSectionType } from '@/lib/types/sections'

export const experienceSection: ExperienceSectionType = {
    title: "where i've worked",
    experiences: [
    {
        company: 'Onenex',
        companyUrl: 'https://www.onenex.co/',
        role: 'SRE Team Lead',
        started: 'July 2022',
        upto: 'present',
        tasks: [
            'Providing the complete cloud architecture (AWS)',
            'Delivering AWS Cloud Managed Services to clients.',
            'Designing, building, and maintaining CI/CD pipelines.',
            'Automating infrastructure provisioning, configuration management, and deployment processes.',
            'Monitoring and troubleshooting production issues.',
            'Ensuring availability, performance, and scalability of systems and services.',
            'Leading a team of SREs to maintain and improve the reliability of the platform.',
        ],
    },
    {
        company: 'Onenex',
        companyUrl: 'https://www.onenex.co/',
        role: 'Development Team Lead',
        started: 'February 2022',
        upto: 'June 2022',
        tasks: [
        'Developing and maintaining the backend services using Laravel and Node.js.',
        'Providing the software architecture between development and SRE teams.',
        'Leading the development team to deliver high-quality software.',
        'Reviewing and approving multiple Pull requests.',
        'Ensuring the team follows best practices and coding standards.',
        'Collaborating with the SRE team to ensure the software is reliable and scalable.',
        'Mentoring junior developers.',
        'DevOps tasks such as setting up CI/CD pipelines, monitoring, and alerting.',
        ],
    },
    {
        company: 'SuperSevenStars',
        companyUrl: 'https://supersevenstars.com/',
        role: 'Development Team Lead',
        started: 'September 2020',
        upto: 'February 2022',
        tasks: [
        'Developed and maintained headless E-commerce websites using Magento 2 and React.',
        'Developed and maintained the sub company websites using Laravel.',
        'Led a team of developers to deliver high-quality software.',
        'Reviewed and approved multiple Pull requests.',
        'Ensured the team followed best practices and coding standards.',
        'DevOps tasks such as setting up CI/CD pipelines, monitoring, and alerting.',
        'Collaborated with clients to understand their requirements and provide solutions.',
        ],
    },
    {
        company: 'NCDDP Myanmar',
        companyUrl: 'https://www.cdd.drdmyanmar.org/',
        role: 'Web Developer and Database Administrator',
        started: 'March 2018',
        upto: 'September 2020',
        tasks: [
        'Integrate the MIS system with CI/CD pipelines to automate the deployment process.',
        'Implementing the versioning for database schema changes to ensure data consistency.',
        'Designing and implementing the database schema.',
        'Automating the database backup and restore process.',
        'Monitoring and troubleshooting database performance issues.',
        'Colloborating between the development and operation teams.',
        'Actively sharing knowledge with the team members to foster a learning culture.',
        ],
    },
    {
        company: 'NCDDP Myanmar',
        companyUrl: 'https://www.cdd.drdmyanmar.org/',
        role: 'M&E and MIS Officer',
        started: 'January 2016',
        upto: 'March 2018',
        tasks: [
        'Data collection, analysis, and reporting.',
        'Maintaining the MIS system.',
        'Managing the MIS database.',
        'Providing training to the users.',
        'Monitoring and evaluating the projects and providing feedback to the management.',
        ],
    },
    {
        company: 'CommunityDevelopmentAssociation',
        companyUrl: 'https://www.cda-myanmar.com/',
        role: 'Database and M&E Officer',
        started: 'May 2011',
        upto: 'December 2015',
        tasks: [
        'Data collection, analysis, and reporting.',
        'Providing training to the users.',
        'Monitoring and evaluating the projects and providing feedback to the management.',
        'Assisting in the development of the MIS system.',
        'Assisting on project proposal writing.',
        'Developed and maintained the organization website.',
        ],
    },
    {
        company: 'InfoSys',
        companyUrl: 'https://www.facebook.com/InfoSysMyanmarOfficial/',
        role: 'IT Support Specialist',
        started: 'May 2010',
        upto: 'April 2011',
        tasks: [
        'Supporting in government IT projects and Network Infrastructure.',
        'Helpdesk support for the users and clients.',
        'Network and system administration.',
        'Software installation, troubleshooting, and bug finding.',
        ],
    },
    ],
};